before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
archives:
  - 'name_template': '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: darwin
        format: zip
      - goos: windows
        format: zip
